cache:
    paths:
        - .composer-cache/
        - build/bin/

variables:
    PHP_IMAGE_LOWER: php:7.2-cli-alpine
    PHP_IMAGE_UPPER: php:7.3-cli-alpine

before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar config -g cache-dir $PWD/.composer-cache

tests:php-lower:
    image: $PHP_IMAGE_LOWER
    script:
        - php composer.phar update --ansi --prefer-lowest --prefer-stable
        - php vendor/bin/phpunit

tests:php-upper:
    image: $PHP_IMAGE_UPPER
    script:
        - php composer.phar update --ansi
        - phpdbg -qrr vendor/bin/phpunit --coverage-text --colors=never
        - "[ -e build/bin/infection ] || curl -Ls https://github.com/infection/infection/releases/download/0.14.2/infection.phar -o build/bin/infection"
        - phpdbg -qrr build/bin/infection --min-msi=84 --min-covered-msi=86 --threads=$(nproc) --ansi --show-mutations --no-progress

integration-tests:
    image: docker:19.03.3
    services:
        - docker:19.03.3-dind
    before_script: []
    variables:
        DOCKER_DRIVER: overlay2
        SOLR_IMAGE: solr:8.2-slim
        SOLR_URL: http://localhost:8983/solr/sample/
    script:
        - cp $PWD/tests/Fixtures/sample.json $PWD/.docker/solr/data
        - docker run -d --name solr -p 8983:8983 -v $PWD/.docker/solr/data:/opt/solr/data -v $PWD/.docker/solr/cores/sample:/sample $SOLR_IMAGE
        - docker exec solr wait-for-solr.sh
        - docker exec solr solr create -V -c sample -d /sample
        - docker exec solr post -c sample data/sample.json
        - >
            docker run --network host -e SOLR_URL=$SOLR_URL -v $PWD:/app -v $PWD/.composer-cache:/.composer-cache -w /app $PHP_IMAGE_UPPER /bin/sh -c "
            curl -sS https://getcomposer.org/installer | php &&
            php composer.phar config -g cache-dir /.composer-cache &&
            php composer.phar update --ansi &&
            php vendor/bin/phpunit --group integration"

code-analysis:
    image: $PHP_IMAGE_UPPER
    script:
        - php composer.phar validate -n --ansi --strict
        - php composer.phar update --ansi
        - "[ -e build/bin/local-php-security-checker ] || curl -sL https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 -o build/bin/local-php-security-checker && chmod +x build/bin/local-php-security-checker"
        - php vendor/bin/ecs check --ansi
        - php vendor/bin/psalm.phar --show-info=true
        - php vendor/bin/phpstan analyse --no-progress --ansi
        - php build/bin/local-php-security-checker --format=ansi
