version: '3.7'

x-php-common:
    &php-common
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
        - HOME
        - COMPOSER_HOME=$HOME/.composer
    volumes:
        - $HOME/.ssh/known_hosts:$HOME/.ssh/known_hosts
        - $HOME/.composer:$HOME/.composer
        - /etc/passwd:/etc/passwd:ro
        - /etc/group:/etc/group:ro
        - $PWD:/app

services:
    php7:
        <<: *php-common
        build:
            context: .docker/php/
            args:
                PHP_VERSION: '7.3-cli-alpine'

    solr:
        image: solr:8.2-slim
        ports:
            - "8983:8983"
        volumes:
            - .docker/solr/data:/opt/solr/data
            - .docker/solr/cores/sample:/sample
        entrypoint:
            - docker-entrypoint.sh
            - solr
            - start
            - -f
